### ISSUE TITLE
能不能加入自动设置代理的功能

### ISSUE THREAD

**Issue by CKrome** [lyx32/gfw.press#1]
如题，就是运行后自动设置代理127.0.0.1:3128，退出后自动取消代理，这样在使用时就会方便很多了😉

**Comment by lyx32** [comment]
我个人并不中意这个功能,原因如下
1.因为要加就需要给ie加代理,
2.而ie加上代理之后,很多你认为很正常的东西,它都会走一遍代理,

其实我个人更倾向于安装一个火狐和谷歌,
火狐全局翻墙,谷歌不走代理.

**Comment by CKrome** [comment]
谢谢回复，你的办法不错，我目前也正在用，是Firefox+Brave，Firefox正常上网，Brave走代理
