### ISSUE TITLE
反馈一个Bug

### ISSUE THREAD

**Issue by CKrome** [lyx32/gfw.press#2]
选择完节点地址点确定之后，再次打开主窗口，这时如果点击取消会导致节点地址恢复到第一个选项。

**Comment by lyx32** [comment]
额,看到了.还真是.

**Comment by lyx32** [comment]
[已修复](https://github.com/lyx32/gfw.press/commit/0e8df0cb2a42b15d9152dd7ea5a8741443798495)

**Comment by CKrome** [comment]
感谢修复，速度真快😊

**Comment by lyx32** [comment]
其实也不算是bug,只是设置默认值而已.
